In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
print("All modules imported successfully")

All modules imported successfully

In [2]:
df=pd.read_csv('./Churn_Modelling.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [7]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [8]:
le_gender=LabelEncoder()
df['Gender']=le_gender.fit_transform(df['Gender'])

In [9]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [10]:
ohe_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=ohe_geo.fit_transform(df[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [11]:
df=pd.concat([df.drop(['Geography'],axis=1),geo_encoded_df],axis=1)

In [12]:
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [13]:
X=df.drop('EstimatedSalary',axis=1)
y=df['EstimatedSalary']

In [14]:
# Save encoder and scaler objects for future use
with open('le_gender.pkl', 'wb') as f:
    pickle.dump(le_gender, f)

with open('ohe_geo.pkl', 'wb') as f:
    pickle.dump(ohe_geo, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(StandardScaler(), f)

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

## ANN Regression Model

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
## Build model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

# Compile model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\Dell\Desktop\codes\Udemy_GenAI\ANN_Project\ann_venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [20]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir='regressionlogs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [22]:
history=model.fit(
X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=32,callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Dell\Desktop\codes\Udemy_GenAI\ANN_Project\ann_venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Dell\Desktop\codes\Udemy_GenAI\ANN_Project\ann_venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 9s 15ms/step - loss: 100377.5078 - mae: 100377.5078 - val_loss: 98515.3438 - val_mae: 98515.3438
Epoch 2/100
250/250 [==============================] - 3s 12ms/step - loss: 99634.5156 - mae: 99634.5156 - val_loss: 97025.3750 - val_mae: 97025.3750
Epoch 3/100
250/250 [==============================] - 3s 11ms/step - loss: 97061.8984 - mae: 97061.8984 - val_loss: 93248.7734 - val_mae: 93248.7734
Epoch 4/100
250/250 [==============================] - 3s 12ms/step - loss: 92011.1172 - mae: 92011.1172 - val_loss: 86945.6250 - val_mae: 86945.6250
Epoch 5/100
250/250 [==============================] - 3s 12ms/step - loss: 84606.9141 - mae: 84606.9141 - val_loss: 78716.3125 - val_mae: 78716.3125
Epoch 6/100
250/250 [==============================] - 2s 9ms/step - loss: 75785.4688 - mae: 75785.4688 - val_loss: 69997.3203 - val_mae: 69997.3203
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 67063.0000 - mae: 67063.0000 - val_loss: 62221.0156 - val_mae: 62221.0156
Epoch 8/100
250/250 [==============================] - 2s 8ms/step - loss: 59914.0117 - mae: 59914.0117 - val_loss: 56493.6406 - val_mae: 56493.6406
Epoch 9/100
250/250 [==============================] - 2s 8ms/step - loss: 55059.2539 - mae: 55059.2539 - val_loss: 53098.9883 - val_mae: 53098.9883
Epoch 10/100
250/250 [==============================] - 3s 12ms/step - loss: 52299.1719 - mae: 52299.1719 - val_loss: 51501.2578 - val_mae: 51501.2578
Epoch 11/100
250/250 [==============================] - 3s 12ms/step - loss: 51071.4414 - mae: 51071.4414 - val_loss: 51011.6680 - val_mae: 51011.6680
Epoch 12/100
250/250 [==============================] - 2s 8ms/step - loss: 50588.6719 - mae: 50588.6719 - val_loss: 50824.0117 - val_mae: 50824.0117
Epoch 13/100
250/250 [==============================] - 2s 10ms/step - loss: 50384.0430 - mae: 50384.0430 - val_loss: 50743.7109 - val_mae: 50743.7109
Epoch 14/100
250/250 [==============================] - 2s 7ms/step - loss: 50271.6406 - mae: 50271.6406 - val_loss: 50691.0586 - val_mae: 50691.0586
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 50195.4531 - mae: 50195.4531 - val_loss: 50653.1641 - val_mae: 50653.1641
Epoch 16/100
250/250 [==============================] - 1s 5ms/step - loss: 50141.7812 - mae: 50141.7812 - val_loss: 50607.9844 - val_mae: 50607.9844
Epoch 17/100
250/250 [==============================] - 2s 7ms/step - loss: 50091.9258 - mae: 50091.9258 - val_loss: 50584.1992 - val_mae: 50584.1992
Epoch 18/100
250/250 [==============================] - 1s 5ms/step - loss: 50047.5078 - mae: 50047.5078 - val_loss: 50554.4648 - val_mae: 50554.4648
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 50008.6602 - mae: 50008.6602 - val_loss: 50517.4141 - val_mae: 50517.4141
Epoch 20/100
250/250 [==============================] - 1s 6ms/step - loss: 49975.3203 - mae: 49975.3203 - val_loss: 50490.8711 - val_mae: 50490.8711
Epoch 21/100
250/250 [==============================] - 2s 8ms/step - loss: 49938.8750 - mae: 49938.8750 - val_loss: 50467.9844 - val_mae: 50467.9844
Epoch 22/100
250/250 [==============================] - 2s 6ms/step - loss: 49909.9492 - mae: 49909.9492 - val_loss: 50451.3711 - val_mae: 50451.3711
Epoch 23/100
250/250 [==============================] - 2s 9ms/step - loss: 49880.7305 - mae: 49880.7305 - val_loss: 50431.5117 - val_mae: 50431.5117
Epoch 24/100
250/250 [==============================] - 1s 6ms/step - loss: 49856.2617 - mae: 49856.2617 - val_loss: 50430.9062 - val_mae: 50430.9062
Epoch 25/100
250/250 [==============================] - 1s 6ms/step - loss: 49834.5625 - mae: 49834.5625 - val_loss: 50415.3320 - val_mae: 50415.3320
Epoch 26/100
250/250 [==============================] - 2s 8ms/step - loss: 49811.7383 - mae: 49811.7383 - val_loss: 50403.5273 - val_mae: 50403.5273
Epoch 27/100
250/250 [==============================] - 1s 5ms/step - loss: 49793.0508 - mae: 49793.0508 - val_loss: 50390.3750 - val_mae: 50390.3750
Epoch 28/100
250/250 [==============================] - 1s 6ms/step - loss: 49773.6797 - mae: 49773.6797 - val_loss: 50377.8438 - val_mae: 50377.8438
Epoch 29/100
250/250 [==============================] - 1s 6ms/step - loss: 49758.6133 - mae: 49758.6133 - val_loss: 50370.4609 - val_mae: 50370.4609
Epoch 30/100
250/250 [==============================] - 2s 7ms/step - loss: 49736.5977 - mae: 49736.5977 - val_loss: 50362.7812 - val_mae: 50362.7812
Epoch 31/100
250/250 [==============================] - 2s 6ms/step - loss: 49720.2969 - mae: 49720.2969 - val_loss: 50355.6562 - val_mae: 50355.6562
Epoch 32/100
250/250 [==============================] - 2s 7ms/step - loss: 49706.5664 - mae: 49706.5664 - val_loss: 50341.2773 - val_mae: 50341.2773
Epoch 33/100
250/250 [==============================] - 1s 5ms/step - loss: 49690.8242 - mae: 49690.8242 - val_loss: 50343.4336 - val_mae: 50343.4336
Epoch 34/100
250/250 [==============================] - 1s 6ms/step - loss: 49676.0312 - mae: 49676.0312 - val_loss: 50334.0117 - val_mae: 50334.0117
Epoch 35/100
250/250 [==============================] - 1s 6ms/step - loss: 49663.8164 - mae: 49663.8164 - val_loss: 50330.1055 - val_mae: 50330.1055
Epoch 36/100
250/250 [==============================] - 2s 9ms/step - loss: 49649.5781 - mae: 49649.5781 - val_loss: 50318.1914 - val_mae: 50318.1914
Epoch 37/100
250/250 [==============================] - 1s 6ms/step - loss: 49636.5000 - mae: 49636.5000 - val_loss: 50313.4648 - val_mae: 50313.4648
Epoch 38/100
250/250 [==============================] - 1s 6ms/step - loss: 49621.5078 - mae: 49621.5078 - val_loss: 50306.3281 - val_mae: 50306.3281
Epoch 39/100
250/250 [==============================] - 1s 6ms/step - loss: 49612.5781 - mae: 49612.5781 - val_loss: 50302.4492 - val_mae: 50302.4492
Epoch 40/100
250/250 [==============================] - 1s 5ms/step - loss: 49600.8125 - mae: 49600.8125 - val_loss: 50306.4922 - val_mae: 50306.4922
Epoch 41/100
250/250 [==============================] - 2s 10ms/step - loss: 49590.8789 - mae: 49590.8789 - val_loss: 50295.2031 - val_mae: 50295.2031
Epoch 42/100
250/250 [==============================] - 2s 10ms/step - loss: 49579.2227 - mae: 49579.2227 - val_loss: 50298.4766 - val_mae: 50298.4766
Epoch 43/100
250/250 [==============================] - 3s 11ms/step - loss: 49570.7422 - mae: 49570.7422 - val_loss: 50297.3672 - val_mae: 50297.3672
Epoch 44/100
250/250 [==============================] - 2s 9ms/step - loss: 49556.9883 - mae: 49556.9883 - val_loss: 50291.9922 - val_mae: 50291.9922
Epoch 45/100
250/250 [==============================] - 2s 10ms/step - loss: 49550.2656 - mae: 49550.2656 - val_loss: 50289.2812 - val_mae: 50289.2812
Epoch 46/100
250/250 [==============================] - 2s 10ms/step - loss: 49540.4102 - mae: 49540.4102 - val_loss: 50294.2734 - val_mae: 50294.2734
Epoch 47/100
250/250 [==============================] - 2s 8ms/step - loss: 49533.3711 - mae: 49533.3711 - val_loss: 50288.4531 - val_mae: 50288.4531
Epoch 48/100
250/250 [==============================] - 1s 6ms/step - loss: 49524.1719 - mae: 49524.1719 - val_loss: 50275.5430 - val_mae: 50275.5430
Epoch 49/100
250/250 [==============================] - 1s 5ms/step - loss: 49516.3867 - mae: 49516.3867 - val_loss: 50289.3789 - val_mae: 50289.3789
Epoch 50/100
250/250 [==============================] - 2s 10ms/step - loss: 49511.0312 - mae: 49511.0312 - val_loss: 50276.7070 - val_mae: 50276.7070
Epoch 51/100
250/250 [==============================] - 3s 11ms/step - loss: 49501.8633 - mae: 49501.8633 - val_loss: 50271.4258 - val_mae: 50271.4258
Epoch 52/100
250/250 [==============================] - 3s 12ms/step - loss: 49492.4883 - mae: 49492.4883 - val_loss: 50270.6133 - val_mae: 50270.6133
Epoch 53/100
250/250 [==============================] - 2s 9ms/step - loss: 49487.3516 - mae: 49487.3516 - val_loss: 50272.9570 - val_mae: 50272.9570
Epoch 54/100
250/250 [==============================] - 2s 8ms/step - loss: 49477.5781 - mae: 49477.5781 - val_loss: 50267.5391 - val_mae: 50267.5391
Epoch 55/100
250/250 [==============================] - 2s 9ms/step - loss: 49474.3320 - mae: 49474.3320 - val_loss: 50273.7539 - val_mae: 50273.7539
Epoch 56/100
250/250 [==============================] - 2s 8ms/step - loss: 49469.2969 - mae: 49469.2969 - val_loss: 50280.9727 - val_mae: 50280.9727
Epoch 57/100
250/250 [==============================] - 1s 5ms/step - loss: 49462.5430 - mae: 49462.5430 - val_loss: 50274.2148 - val_mae: 50274.2148
Epoch 58/100
250/250 [==============================] - 2s 6ms/step - loss: 49453.0742 - mae: 49453.0742 - val_loss: 50275.9805 - val_mae: 50275.9805
Epoch 59/100
250/250 [==============================] - 2s 7ms/step - loss: 49447.3594 - mae: 49447.3594 - val_loss: 50285.1367 - val_mae: 50285.1367
Epoch 60/100
250/250 [==============================] - 2s 9ms/step - loss: 49440.0781 - mae: 49440.0781 - val_loss: 50282.2383 - val_mae: 50282.2383
Epoch 61/100
250/250 [==============================] - 2s 9ms/step - loss: 49437.8672 - mae: 49437.8672 - val_loss: 50270.7070 - val_mae: 50270.7070
Epoch 62/100
250/250 [==============================] - 1s 5ms/step - loss: 49430.3906 - mae: 49430.3906 - val_loss: 50281.5000 - val_mae: 50281.5000
Epoch 63/100
250/250 [==============================] - 2s 9ms/step - loss: 49425.9375 - mae: 49425.9375 - val_loss: 50281.2344 - val_mae: 50281.2344
Epoch 64/100
250/250 [==============================] - 2s 8ms/step - loss: 49423.5000 - mae: 49423.5000 - val_loss: 50288.0234 - val_mae: 50288.0234

In [23]:
%load_ext tensorboard

In [25]:
%tensorboard --logdir=regressionlogs/fit

In [26]:
## Evaluate the model
loss, mae = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}, Test MAE: {mae}")

63/63 [==============================] - 0s 6ms/step - loss: 50267.5391 - mae: 50267.5391
Test Loss: 50267.5390625, Test MAE: 50267.5390625